### ISSUE TITLE
README.md file out of date compared to pom.xml in master

### ISSUE THREAD

**Issue by holdorph** [IMSGlobal/basiclti-util-java#13]
The README.md file in master currently mentions the dependency you should use as:

    <dependency>
        <groupId>org.imsglobal</groupId>
        <artifactId>basiclti-util</artifactId>
        <version>1.0.0</version>
    </dependency>

However, in the pom.xml file in master defines the artifact as:

    <groupId>org.imsglobal</groupId>
    <artifactId>basiclti-util</artifactId>
    <version>1.1.1</version>

There is a discrepancy between the '1.1.1' and the '1.0.0'.  I believe it is the README.md file that should be changed.

**Comment by pfgray** [comment]
Thanks, @holdorph!
