### ISSUE TITLE
Incorrect usage outline in the readme

### ISSUE THREAD

**Issue by stormtek** [IMSGlobal/basiclti-util-java#17]
In the usage for a provider, for verifying a user, the readme states that you should use

`LtiVerificationResult ltiResult = ltiVerifier.verify(request, request.getParameter("oauth_consumer_key"));`

when in reality you want to use

`LtiVerificationResult ltiResult = ltiVerifier.verify(request, secret_key);`

where `secret_key` is the stored secret key for the consumer who is making the request. This is confusing and should be updated.

**Comment by pfgray** [comment]
You are right! It must've been late when I made these docs :)

thanks!
