### ISSUE TITLE
servlet-api maven dependency should have scope "provided"

### ISSUE THREAD

**Issue by svella** [IMSGlobal/basiclti-util-java#18]
At runtime, servlet-api is supposed to be provided by the servlet container and not bundled in any war, ear, etc. The default maven dependency scope is compile, which will automatically and transitively pulled servlet-api into war files unless scope is set to provided.

```
<dependency>
     <groupId>javax.servlet</groupId>
     <artifactId>servlet-api</artifactId>
     <version>2.5</version>
     <scope>provided</scope>
</dependency>
```

While It can be worked around by specifically excluding in downstream pom files, it is poor behavior for a library to declare it with scope other than provided.

**Comment by svella** [comment]
Fixing the documentation did not fix this - it has to be a change to pom.xml.

**Comment by pfgray** [comment]
Yup, I mistakenly referenced this in a commit, sorry about that

**Comment by svella** [comment]
Thx, Paul!

**Comment by pfgray** [comment]
No problem, sorry it took so long...

I plan on releasing what's on master to 1.2.0 at the end of the week
