### ISSUE TITLE
replaceResultRequest is invalid: imsx_messageIdentifier missing

### ISSUE THREAD

**Issue by josiasmontag** [IMSGlobal/basiclti-util-java#27]
The [replaceResultRequest XML template ](https://github.com/IMSGlobal/basiclti-util-java/blob/f8218f2d1184441cd3be5b5b08ab8af6a885d3e4/src/main/java/org/imsglobal/pox/IMSPOXRequest.java#L510) is currently not valid. According to the [implementation guide](https://www.imsglobal.org/specs/ltiv1p1p1/implementation-guide) there should be an `imsx_messageIdentifier` key.

I have encountered this problem when implementing an LTI tool for edX. The LTI implementation of edX seems to check this key. It throws the following error if the identifier is missing:

```
Failed to parse imsx_messageIdentifier from XML request body
```

**Comment by GenghisZahn** [comment]
I have also run into this issue when attempting to return a score to Agilix Buzz.

**Comment by pfgray** [comment]
version `1.2.0` was released, which fixes this issue: https://search.maven.org/#artifactdetails%7Corg.imsglobal%7Cbasiclti-util%7C1.2.0%7Cjar
