### ISSUE TITLE
How to send events to server

### ISSUE THREAD

**Issue by suresh777** [IMSGlobal/basiclti-util-java#32]
I added caliper library in android application,i configured url in defaults class,i want to send custom events to server,please provide event structure

**Comment by pfgray** [comment]
Hi @suresh777 , This library is specific to LTI, it doesn't provide any mechanisms for sending caliper events.

You might have better luck asking on the [caliper-java](https://github.com/IMSGlobal/caliper-java-public/issues) repository. 

As far as I know there are many Jackson entity objects in that repository which will take care of formatting the events for you.
